### ISSUE TITLE
Scam Repository, Copyright violation

### ISSUE THREAD

**Issue by ivancheng1214** [marceloogeda/react-graphql-example#1]
This is the exact copy of https://github.com/apollographql/graphql-tutorial
What's happening here...

**Comment by marceloogeda** [comment]
Hi @ivancheng1214! It's not a copyright violation. 

I built this repository when I was studying about Graphql + React. 
I've followed this steps who was posted on the Apollo's blog.
You can see it here. https://dev-blog.apollodata.com/full-stack-react-graphql-tutorial-582ac8d24e3b
